### ISSUE TITLE
TypeError if value is just list with primitive items

### ISSUE THREAD

**Issue by askerka** [rafa-acioly/animal_case#3]
Hi!
Here example:
```
{
    "productCategories": [1, 2, 3]
}
TypeError: Invalid data type, use list or dict
```

**Comment by askerka** [comment]
Possible solution here https://github.com/rafa-acioly/animal_case/pull/4

**Comment by rafa-acioly** [comment]
thank you very much, can you include a test for it?

**Comment by askerka** [comment]
Sure

**Comment by askerka** [comment]
Hi! @rafa-acioly 
Please, have a look to tests.
By the way, what do you think about that library can't parse data with list as a container
```
[
    {
        'first_key': 'value'
    }
]
```
Is it issue or by design?

**Comment by rafa-acioly** [comment]
@asduj this is the intention, the main idea is converting only dicts and not lists of dicts, but we can do it...you think that it will be useful?

**Comment by askerka** [comment]
@rafa-acioly Sometimes it can useful to parse list of dictionaries when working with inner portion of big json object

**Comment by rafa-acioly** [comment]
i've open a issue (#5) to implement this 👍

**Comment by rafa-acioly** [comment]
the PR #4 have been merged, thank you for your help! :)
